### ISSUE TITLE
New Install of Silverstripe and can't get it to work.

### ISSUE THREAD

**Issue by 8wgremlin** [jeffwhitfield/silverstripe-bootstrap-theme#2]
I've a completely clean new install from silverstripe.
I've downloaded and created the theme as per the instructions.
I've changed the Page.php as required.

The page loads, but doesn't use the theme templates, it uses the Debug template.
It creates the site.css and the site.js fine and places them into the Debug template.

Any ideas on why it isn't using the themes Page.ss ?

**Comment by jeffwhitfield** [comment]
Hi Mat,

It's been a while since I've played with this addon. I'll run a clean install and test it to make sure all is working ok with the latest version of Bootstrap.  

In the meantime, did you check to make sure your SilverStripe config is set to load the new theme you created?

**Comment by jeffwhitfield** [comment]
Ok, just loaded a fresh copy of SilverStripe and added the Bootstrap theme. Everything appears to work just fine. So, to debug your problem, here a few things to check out:
- Double-check the bower_components directory within your theme. Make sure all assets required are present.
- Make sure you've compiled the site.less file using whatever LESS processor you prefer
- Update your config.yml settings with the correct theme.

Also, you might want to check the bower.json file and update the version numbers for the dependencies. It's probably set with older versions and might not be to your liking. Just update the versions and run a bower update.
